name: Format Code

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: Checkout
        uses: actions/checkout@v4
      - run: go fmt ./...
      - name: go generate (clang-format)
        run: go generate ./...
      - name: Display missing format changes
        run: git diff --exit-code
